### ISSUE TITLE
Bug with variable "performance" on Safari for Javascript version

### ISSUE THREAD

**Issue by blaseur** [cupslab/neural_network_cracking#1]
If you execute worker.min.js in Firefox or Chromium, it works fine.

However, in Safari, you get:
worker.min.js:227:89ReferenceError: Can't find variable: performance

Remediation: If you replace the two instance of "performance.now()" with 0, the code works. You just don't get the timing data for how long the call took.

**Comment by wrmelicher** [comment]
Fixed in latest safair/ios by commit dda419f4fa0a2b5b657f670648f11bb11c986178
