### ISSUE TITLE
Can the docker run well？There are some error about the keras version。

### ISSUE THREAD

**Issue by ThomasRaymond** [cupslab/neural_network_cracking#14]
I have try to build the nvidia-docker by      
./deploy.py build-gpu  
 ./deploy.py run-gpu.

But it can't work well.
Logs:

======================================================================
FAIL: test_build_model_deep (__main__.TrainerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pwd_guess_unit.py", line 809, in test_build_model_deep
    t.build_model()
  File "/nn/pwd_guess.py", line 1286, in build_model
    go_backwards=self.config.train_backwards))
  File "/usr/local/lib/python3.5/dist-packages/Keras-0.2.0-py3.5.egg/keras/layers/recurrent.py", line 510, in __init__
    super(JZS1, self).__init__(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Keras-0.2.0-py3.5.egg/keras/layers/core.py", line 23, in __init__
    assert kwarg in {'input_shape'}, "Keyword argument not understood: " + kwarg
AssertionError: Keyword argument not understood: go_backwards

======================================================================
FAIL: test_build_model_deep_no_layers (__main__.TrainerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pwd_guess_unit.py", line 815, in test_build_model_deep_no_layers
    t.build_model()
  File "/nn/pwd_guess.py", line 1286, in build_model
    go_backwards=self.config.train_backwards))
  File "/usr/local/lib/python3.5/dist-packages/Keras-0.2.0-py3.5.egg/keras/layers/recurrent.py", line 510, in __init__
    super(JZS1, self).__init__(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Keras-0.2.0-py3.5.egg/keras/layers/core.py", line 23, in __init__
    assert kwarg in {'input_shape'}, "Keyword argument not understood: " + kwarg
AssertionError: Keyword argument not understood: go_backwards

----------------------------------------------------------------------
Ran 159 tests in 25.580s

**Which versions of keras and  theano should i use?**

**Comment by ThomasRaymond** [comment]
@jtan189 @wrmelicher hello! There are some problems about the usage of docker.

**Comment by m33x** [comment]
Due to GDPR the blog post is currently down (we are fixing this). But here is a mirror describing a working keras/theano configuration.
https://res.mobsec.rub.de/files/Password_Guessing_using_Recurrent_Neural_Networks_-_Password-Guessing.org_-_Blog.pdf

**Comment by jtan189** [comment]
Hi @ThomasRaymond,

I've made a few changes that should improve docker support: https://github.com/jtan189/neural_network_cracking/tree/add-docker-support

The change that is probably most relevant to your issue is that seya is now installed using python3. You can try it out and see if it fixes your issue.

**Comment by ThomasRaymond** [comment]
@jtan189 Thank you！It did solve my problem.
@m33x  Thank you for your tutorial!And there are some problems about the version of seya.Please put it into the readme to prevent other people's mistakes.

**Comment by m33x** [comment]
@ThomasRaymond  "And there are some problems":
okay which problems are there? What should I add to the ReadMe?

**Comment by ThomasRaymond** [comment]
@m33x   you can see the detail in #15 ,jtan189 have point out the problems.
The seya should be installed as:
    git clone https://github.com/EderSantana/seya.git && \
    cd seya && \
    git checkout 49d1bfd66f7442b7ce09dc86f7e78a32b132dd48 && \
    python3 setup.py install

**Comment by m33x** [comment]
@ThomasRaymond no worries, we are all good! this is part of the tutorial since day 1.

We always did it this way. We always used python3 and used the very same commit.

Checkout and try to understand what a Python virtual environment is. And even commit 49d1bf is the same I use and mentioned in the tutorial.

😬👍
