### ISSUE TITLE
worker.min.js doesn't work on Microsoft Edge / IE

### ISSUE THREAD

**Issue by blaseur** [cupslab/neural_network_cracking#2]
On Edge, line 215 of worker.min.js throws the error "Object doesn't support property or method 'jscomp_symbol_iterator0'"

This error is not thrown on Firefox, Chromium, or Safari.

**Comment by wrmelicher** [comment]
Fixed in latest IE/edge by commit dda419f4fa0a2b5b657f670648f11bb11c986178
