### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by tianhao199703** [cupslab/neural_network_cracking#27]
I have problem when I run command: python3 ../pwd_guess.py --config-args guess_len8_config.json

Traceback (most recent call last):
  File "pwd_guess_unit.py", line 30, in <module>
    import pwd_guess
  File "/backup/AI_dicgen/tianhao/data_files/fastleancode/neural_network_cracking/pwd_guess.py", line 50, in <module>
    import generator
ModuleNotFoundError: No module named 'generator'

I tried to use pip but it was failed:
ERROR: Could not find a version that satisfies the requirement generator (from versions: 0.1-alpha.linux-x86_64)
ERROR: No matching distribution found for generator

Please help me 
Thanks

**Comment by mmahmad** [comment]
Hi, I'm facing the same problem. Could you please share how you resolved this? I installed all packages from `requirements-cpu.txt` but still face this error.

**Comment by mmahmad** [comment]
Installing the `test-generator` package worked.
