### ISSUE TITLE
Keras Version Problem

### ISSUE THREAD

**Issue by qingyuanxingsi** [cupslab/neural_network_cracking#3]
Much thanks for sharing your code, during my experiment using your code, I found that your code do not work with the latest **keras** version, the import location of slice_X is wrong and Bidirectional RNN layers could not be found.Would you be so kind as to specify the version of your keras used.

**Comment by wrmelicher** [comment]
Version 0.2.0 should work. The bidirectional RNN can be found in seya. https://github.com/EderSantana/seya
